In [ ]:
# Welcome to the NumPy Workshop!

## Introduction

NumPy is a powerful library for scientific computing in Python. It provides support for multi-dimensional arrays and matrices, along with a wide range of mathematical operations to manipulate them. In this workshop, we'll be covering some of the basics of NumPy, but don't worry, it won't be too square!

## Getting Started

Before we dive in, let's import NumPy and give it a nickname for easier typing:

import numpy as np

Now we're ready to rock and roll!

## Creating Arrays

To create a NumPy array, we can simply pass a Python list to the np.array() function. Let's create an array of integers:

my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

Output:
[1 2 3 4 5]

Wow, that was easy peasy lemon squeezy!

But what if we want to create an array of floats instead? Easy cheesy!

my_float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
print(my_float_array)

Output:
[1.1 2.2 3.3 4.4 5.5]

Now we're cooking with gas!

## Array Operations

One of the great things about NumPy is that it provides a wide range of mathematical operations to manipulate arrays. Let's take a look at some of the most common ones:

### Addition

To add two arrays together, we can simply use the + operator. Let's create two arrays and add them together:

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])
array_sum = array_1 + array_2
print(array_sum)

Output:
[5 7 9]

### Subtraction

Subtracting arrays is just as easy. Let's subtract array_2 from array_1:

array_diff = array_1 - array_2
print(array_diff)

Output:
[-3 -3 -3]

### Multiplication

To multiply two arrays together, we can use the * operator. Let's create two arrays and multiply them together:

array_3 = np.array([2, 4, 6])
array_4 = np.array([1, 3, 5])
array_product = array_3 * array_4
print(array_product)

Output:
[ 2 12 30]

### Division

Dividing arrays is a piece of cake. Let's divide array_3 by array_4:

array_quotient = array_3 / array_4
print(array_quotient)

Output:
[2.         1.33333333 1.2       ]

NumPy sure knows how to divide and conquer!

## Conclusion

And that's a wrap! We hope you've enjoyed this workshop on NumPy. Remember, if you have any questions, don't be afraid to ask. We're always here to lend a helping hand. Keep calm and NumPy on! 🧮🤖
